### ISSUE TITLE
Would like to see artifactCleanup have a parameter to specify groupId

### ISSUE THREAD

**Issue by tpbradt** [JFrogDev/artifactory-user-plugins#114]
We are looking at implementing the artifactCleanup plugin in the near future, but not without an enhancement.  It allows specifying the repo, but we need to limit the groupId as well.  We are a global company with software groups in different parts of the globe working on different products.  We want to cleanup our artifacts without impacting theirs.  So we need to have groupId as another parameter.

**Comment by aaronsrhodes** [comment]
JFrog does not maintain these user-submitted plugins, but you are free to modify them in any way you see fit. Another way you might accomplish this goal is through the [CLI](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI) and [AQL](https://www.jfrog.com/confluence/display/RTF/Artifactory+Query+Language). See here: https://github.com/JFrogDev/artifactory-scripts/tree/master/cleanup

**Comment by tpbradt** [comment]
Oh, sorry...didn't think about the fact it was under artifactory-USER-plugins.  :)  OK.  We will look into the other option, else fork this and customize ourselves.  Thanks
