### ISSUE TITLE
cleanup/artifactCleanup: 'cleanup.skip' property support

### ISSUE THREAD

**Issue by axel3rd** [JFrogDev/artifactory-user-plugins#115]
Hello,

To control the growth of Artifactory storage in the time, the cleanup plugin is very useful.

But the policy of clean could depend of artifacts, some of one should not be deleted even if not downloaded since some months (legal archive of code produced, old company framework version used less once  by year, ...).

It could be useful to support a **cleanup.skip** [Artifactory property](https://www.jfrog.com/confluence/display/RTF/Properties), who disable the delete when found on artifact.
In this case any users have autonomy to participe to artifacts deletion in autonomy on their artifacts (depending permissions).

-------
Currently in Artifactory, when a property is setted **Recursive**, it is applied on current childrens BUT NOT on new childrens artifacts deployed after this property configuration.
=> Perhaps parent paths should be checked to verify the presence of this property.

----

This property check process (based on [REST api](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ItemProperties) ?) could perhaps extend the global cleanup process time => a `properties.support= true` in [artifactCleanup.properties](https://github.com/JFrogDev/artifactory-user-plugins/blob/master/cleanup/artifactCleanup/artifactCleanup.properties) would be a good idea.

-------

I know that user plugins are not under JFrog maintenance ; this issue is a personnal reminder or for a motivated user (^^), and for sharing the idea/specification.

NB: It could be a partial answer for #114.

Best regards

**Comment by markgalpin** [comment]
Just to clarify:  JFrog doesn't typically add features etc. to user plugins submitted here.  What we DO DO is provide testing services, and we WILL update them if a new version of the product breaks them, or provide a formal deprecation notice if the product does something that replaces the capability.  We do this as a courtesy to our community to encourage people to contribute their changes back.

**Comment by axel3rd** [comment]
**NB**: Rather than search parent properties on each artifacts to determine if artifact is skipped or not (could be long if many artifacts) ; using [AQL](https://www.jfrog.com/confluence/display/RTF/User+Plugins#UserPlugins-IncludingAQLQueries) for search all folders where property is defined could perhaps be better (this property usage stay an exception). It is only a path match in the result list after that.

AQL query:
```
items.find(
    {
        "repo":"repoKey",
        "type": "folder",
        "@cleanup.skip":"true"
    }
).include("path", "name")

// Complete folder path is $path/$name in result
```

**Comment by markgalpin** [comment]
Once you start doing stuff like this, it starts to beg the question as to why not just use the CLI on a cron to delete things based on an AQL query?

**Comment by axel3rd** [comment]
@markgalpin: This is an excellent question :smile:. Initially I wanted create a Java Batch (using [artifactory-client-java](https://github.com/JFrogDev/artifactory-client-java)) only for my need, until discover the user plugins, and mainly *cleanup/artifactCleanup*.

IMO updating *cleanup/artifactCleanup* user plugin could be a good solution because:
* Server side internal job is better than client side processus (more sustainable).
* Algorithm is required => some shell script (or another language) will be used in addition of CLI + AQL.
* This skip option could be useful for others companies (I'm sure I'm not alone to have the need to establish a cleanup strategy on repositories with several hundred thousand artifacts representing more than 1 To by repository ... with this particularity of skip someone)

WDYT ?

**Comment by markgalpin** [comment]
I agree the skip will be useful for a number of customers, and I quite like the feature idea and would urge acceptance of the PR if you file it -- I just wanted to make sure you'd considered both options for your own purposes.
In general at the moment we recommend running the CLI with AQL as the most powerful mechanism for complex policy application.  I think your first two points really are about what makes you feel comfortable as an admin than a best practice issue per se.  The big advantage to being a client-side job (run on the server) is that because user plugins run in-process they potentially have less protection against bugs harming the server than client-side code does.  Although in this case that advantage is more theoretical than realized.

**Comment by axel3rd** [comment]
Agree with precision. But if this option could be useful for other, I will be happy.

I will try to work on the PR before end of next week (I'm a little newbie in Groovy, I need before play with user plugins mechanism to provide a correct PR).

**Comment by axel3rd** [comment]
> This property check process (based on REST api ?) could perhaps extend the global cleanup process time => a properties.support= true in artifactCleanup.properties would be a good idea.

Not really true with the previous AQL query (to retrieves which folders have the property) ; tested on a big Artifactory instance.
In addition, if the *activation* is forgot in configuration and some users have define the property, some important artifacts could be deleted.

=> Reverse strategy, I will add a **disablePropertiesSupport** parameter (default: *false*).

**Comment by axel3rd** [comment]
This issue could be closed, #122 is merged :-).

**Comment by rahulaich** [comment]
I am finding it difficult to use the property cleanup.skip. Can someone please post an usage example of this property. I am using REST API to perform the cleanup.

**Comment by axel3rd** [comment]
@rahulaich : 

There is misunderstanding ... in the plugin execution or API call, the only [parameter](https://github.com/JFrogDev/artifactory-user-plugins/tree/master/cleanup/artifactCleanup#parameters) usable is **disablePropertiesSupport**, to disable the support of some [properties](https://github.com/JFrogDev/artifactory-user-plugins/tree/master/cleanup/artifactCleanup#artifactory-properties-support) defined in Artifactory UI, who could have an effect on default cleanup behavior.

**cleanup.skip** (=true) should be defined in Artifactory UI, in properties tab, for a directory or component:
![image](https://user-images.githubusercontent.com/2912441/33185024-37803272-d080-11e7-8d2c-a3b0edfcce63.png)

Result:
![image](https://user-images.githubusercontent.com/2912441/33185031-3e3ef1f2-d080-11e7-946a-600bb2d89bec.png)

So any user could define this properties on their own components, and these one will not be deleted during cleanup process (except if *disablePropertiesSupport* is setted to *true* for plugin execution or API call).
