### ISSUE TITLE
urls field in index.yaml uses local://

### ISSUE THREAD

**Issue by rcorre** [JFrogDev/artifactory-user-plugins#190]
The `urls` field in the generated `index.yaml` looks like:

```
    urls:
    - local://webapp-0.2.3.tgz
```

Instead of `local://`, it should have the path to download the chart from artifactory.

**Comment by elioengcomp** [comment]
@rcorre which Artifactory user plugin are you referring to?

**Comment by rcorre** [comment]
I've realized this may not be the right place. I think the one we're using is part of artifactory. Sorry!
