### ISSUE TITLE
Conda plugin returns index errors with authentication

### ISSUE THREAD

**Issue by ablack-jpl** [JFrogDev/artifactory-user-plugins#200]
When attempting to search an artifactory conda channel with authentication, a CondaIndexError is returned. 

Command:

````
conda search --override-channels --channel https://<user>:<API Key / Encrypted Pass>@<server>/artifactory/<repo>/<channel>
````

Response:

````
Loading channels: failed

CondaIndexError: Invalid index file: https://<user>:<API Key / Encrypted Pass>@<server>/artifactory/<repo>/<channel>/osx-64/repodata.json: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
````

This error was originally returned for the noarch subdirectory, and that error was handled by creating the repodata.json as described in #161. After solving, it is now returned with the osx-64 repo as indicated above.

**Comment by elioengcomp** [comment]
Hi @ablack-jpl 

Is that a local or remote repo? Do you have packages deployed there? Can you see in Artifactory the 
repodata.json file the client is complaining about?

**Comment by ablack-jpl** [comment]
It's a local repo that I have packages deployed to. These packages are searchable / retrievable with anonymous access.

I can see the repodata.json at the <repo>/<channel>/osx-64 level. This was auto-generated by the plugin after uploading a tar.bz2 to the osx-64 arch endpoint. I have reproduced it below (we're testing use cases with boring packages atm).

````
{
    "info": {

    },
    "packages": {
        "pyinstrument-0.13.1-py27_0.tar.bz2": {
            "subdir": "osx-64",
            "md5": "4a4e71b5f9514178f152b8201b031cb7",
            "depends": [
                "python >=2.7,<2.8.0a0"
            ],
            "version": "0.13.1",
            "license": "BSD",
            "sig": null,
            "build": "py27_0",
            "build_number": 0,
            "size": 50390,
            "name": "pyinstrument"
        }
    }
}
````

**Comment by ablack-jpl** [comment]
Took some time for further digging, and no longer believe the problem is related to this plugin.

Issue only occurs under python3, and only when the total length of the url is greater than 120 characters (including user and api key). Debug output indicates an encoding error in urllib. Sorry for misattributing the cause.

**Comment by elioengcomp** [comment]
@ablack-jpl I'm glad you found the cause of the issue. Thanks for providing this feedback.
