### ISSUE TITLE
Need rest api to enable / disable buildSync and SecurityReplication

### ISSUE THREAD

**Issue by r0ckyte** [JFrogDev/artifactory-user-plugins#207]
I was reading through the documentation and interested to know if there is any REST to disable buildSync and securityreplication once they are up and running ?

**Comment by elioengcomp** [comment]
Hi @r0ckyte 

Those plugins don't have this feature.

Best.
Elio

**Comment by r0ckyte** [comment]
Thanks for the update @elioengcomp 
any suggestions / workarounds for achieving it ?

**Comment by elioengcomp** [comment]
@r0ckyte I can't think on anything besides disabling replications in the configuration files and reloading the plugins. Note that, in order to reload the plugins without changing their contents, you need to `touch` the groovy file.

**Comment by r0ckyte** [comment]
Thank you @elioengcomp
