### ISSUE TITLE
security replication error with artifactory 5.10.4

### ISSUE THREAD

**Issue by r0ckyte** [JFrogDev/artifactory-user-plugins#208]
i'm trying to implement security replication on 5.10.4 version and i'm getting below message on master node. i have downloaded latest source from this repository which was working with 5.9 and not with 5.10.4

artifactory.log:
```
2018-05-06 15:00:00,078 [art-exec-1] [DEBUG] (securityReplication :498) - MASTER: upList size: 2, distList size: 2
2018-05-06 15:00:00,079 [art-exec-1] [DEBUG] (securityReplication :503) - MASTER: Available instances are: [http://172.17.0.3:8081/artifactory:[version:[5.10.4]], http://172.17.0.2:8081/artifactory:[version:[5.10.4]]]
2018-05-06 15:00:00,080 [art-exec-1] [ERROR] (securityReplication :510) - MASTER: Cannot continue, Artifactory version is too new; please update this plugin
2018-05-06 15:00:00,085 [http-nio-8081-exec-4] [DEBUG] (securityReplication :119) - SLAVE: secRepPing is called
```

apart from this, i'm getting permission denied message while executing validation, however i was able to execute **distSecRep**

```
my-id@localhost:~$ curl -uadmin:password -XPOST http://localhost:8081/artifactory/api/plugins/execute/secRepValidate
{
  "errors" : [ {
    "status" : 405,
    "message" : "You are not permitted to execute 'secRepValidate'."
  } ]

```

**Comment by DarthFennec** [comment]
We've currently only tested that plugin on up to  5.10.3, but we should have results for 5.10.4 soon.

Basically, there was a problematic instance in the past where an inconsistency with a newer version of Artifactory lead to potential accidental data deletion conditions. We're safeguarding against that happening in the future by disabling the plugin by default on versions of Artifactory that we haven't tested it on yet. You can read more about it in the [plugin's readme](https://github.com/JFrogDev/artifactory-user-plugins/tree/master/security/securityReplication#upgrading) (in particular, the last paragraph in that "Upgrading" section).

Apologies for the inconvenience.

**Comment by DarthFennec** [comment]
The plugin has been tested and updated. Let us know if you have further issues. Thanks!

**Comment by r0ckyte** [comment]
thanks again @DarthFennec

**Comment by r0ckyte** [comment]
currently i security replication is setup and i can see the sync between 2 instances of artifactory as per the CRON setting hourly. 

do you have any REST call which will sync on demand ? i checked the README but i couldnt see any such option

**Comment by DarthFennec** [comment]
Is there any particular reason you need to sync on demand? There is a call that we use for testing:

```
POST /artifactory/api/plugins/execute/testRunSecurityReplication
```

It isn't designed to be used for anything but testing, though, which is why it's undocumented. You have to run it against your highest priority instance, otherwise it won't do anything. Also I'd advise against running it at the same time that a cron-triggered replication is running, since they can overlap and potentially cause weird things to happen. I doubt it'll create problems, but I don't actually know for sure, and it's not a supported use case.

Personally I'd suggest just going with the cron unless there's a good reason not to.
