### ISSUE TITLE
Wrong curl example for cleanup/buildCleanup

### ISSUE THREAD

**Issue by melkamar** [JFrogDev/artifactory-user-plugins#42]
The example REST call is 
`// curl -f -XPOST -u admin:password "http://localhost:8080/artifactory/api/plugins/execute/cleanBuilds?params=days=50&dryRun=1"`, but then dryRun=1 parameter does not get handled as expected. 

The correct call seems to be `// curl -f -XPOST -u admin:password "http://localhost:8080/artifactory/api/plugins/execute/cleanBuilds?params=days=50|dryRun=1"` with a `|` pipe instead of ampersand

**Comment by DarthFennec** [comment]
Thanks, fixed.
