### ISSUE TITLE
Cleanup enhancements

### ISSUE THREAD

**Issue by dspartz** [JFrogDev/artifactory-user-plugins#46]
In our very large Artifactory instance, the artifactCleanup script hammered the disk too much. I added optional pacing controls, and operational controls to pause, resume, stop, or adjust the pacing value.

In addition, the current script only supports one policy for the entire Artifactory instance. I added support for multiple policies.

These changes are submitted in PR https://github.com/JFrogDev/artifactory-user-plugins/pull/45

**Comment by dspartz** [comment]
Any news on merging this? Can I get an ETA?

**Comment by DarthFennec** [comment]
Sorry, I hadn't really had time to look at this until today. Just merged.
