### ISSUE TITLE
artifactCleanup scheduled job defined in source code

### ISSUE THREAD

**Issue by dspartz** [JFrogDev/artifactory-user-plugins#57]
The CRON scheduled job is defined in the source code, but would be better as configurable via properties file.

Further all policies are scheduled on a single CRON.

The pull request used on commit solves these two issues, making the plugin more easily configurable and not requiring the script to be changed.

**Comment by DarthFennec** [comment]
It's been two months, I'm going to close this.

**Comment by meedel** [comment]
Please explain the cron settings used in the properties file.
It's not 'standard' linux cron layout!

**Comment by dspartz** [comment]
It uses the Quartz specification, searching I found this useful: http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html
