### ISSUE TITLE
securityReplication: Cannot distribute plugin using an admin API key

### ISSUE THREAD

**Issue by ometa** [JFrogDev/artifactory-user-plugins#72]
This is related to the [securityReplication plugin](https://github.com/JFrogDev/artifactory-user-plugins/tree/master/security/securityReplication).

When initially distributing the plugin, the API call to `distSecRep` must be done using the username and password of an admin user that is present on all instances.  I had expected to be able to use an API key in the request, but that does not allow the plugin to propagate to other instances unless that exact same API key is present for the same user in the other instances.

Does not work:
```bash
$ curl -uadmin:<API_KEY> -XPOST http://localhost/artifactory/api/plugins/execute/distSecRep
```

Works as long as the admin user has a password of 'password' across all instances of the mesh:
```bash
$ curl -uadmin:<PLAINTEXT_PASSWORD> -XPOST http://localhost/artifactory/api/plugins/execute/distSecRep
```

**Comment by edwardl50** [comment]
Hi Devin,

This the part of the initial inherent design of the plugin which may be
resolved in future artifactory/plugin releases, however; as the admin user,
I would suggest that they propagate the plugin originally with the plain
text password, allow all the api key's to get synced up, and then propagate
again using the API_KEY which would be in sync by then and change the plain
text.

Regards,
Edward Lo

**Comment by ometa** [comment]
Thanks @edwardl50 for the quick response.  What you suggest is exactly what I ended up doing.  I will submit a PR containing additional setup verbiage that explains the nuances of setting up this plugin so others may benefit.

**Comment by ometa** [comment]
@edwardl50 here you go: https://github.com/JFrogDev/artifactory-user-plugins/pull/73

**Comment by DarthFennec** [comment]
Closing this issue; as the PR was merged, this seems resolved.
