### ISSUE TITLE
User plugins not working with Artifactory upgrade 5.1.0

### ISSUE THREAD

**Issue by Roshang33** [JFrogDev/artifactory-user-plugins#78]
Hi the ArtifactCleanup and other plugins have stopped working after the upgrade to 5.1.0

The logs show that the plugins were successfully registered but trying to execute a function causes a HTTP 400 BAd request error

**Comment by DarthFennec** [comment]
The artifactCleanup plugin seems to work just fine in 5.1.0 on my end. This makes me think one of the other plugins may be causing the issue. Could you provide a list of all the plugins you have installed?

Considering the 400 Bad Request status, it's also possible that your request is incorrect. If you haven't already, please double check that the URL is typed correctly, and that you're properly providing any required parameters.

**Comment by edpeixoto1** [comment]
Rasika,

 

Please work with Travis and update our list with the customers using those plugins.

 

Thanks,

 

Ed

**Comment by Roshang33** [comment]
Yes so that is what I though too a bad request would usually mean url is incorrect however when I post a request on a browser as such http://localhost:8081/artifactory/api/plugins I get the json response with the plugin functions
So I tried the curl command
curl -i -uadmin:password -X POST "http://localhost:8081/artifactory/api/plugins/execute/cleanup?params=months=1|repos=libs-release-local|dryRun=true|paceTimeMS=2000"
And I get the bad request error .I am using a windows 32bit curl.exe also If I were to simply call the function as such curl -i -uadmin:password -X POST "http://localhost:8081/artifactory/api/plugins/execute/cleanup? with hardcoded parameters the function executes fine . So the problem seems to be with multiple parameters again these parameters have been defined so I am thinking it is the  special character | that is the problem

**Comment by DarthFennec** [comment]
Ahh yes, I think I have seen something like this before. Try using the `;` character instead of a `|`, that might work better.

**Comment by Roshang33** [comment]
Yes this seems to have fixed the problem

**Comment by DarthFennec** [comment]
Excellent. I'll close this, then. Thanks!

**Comment by DarthFennec** [comment]
After looking further into it, it seems that this is happening due to a change in Tomcat (as explained [here](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory5.0) and [here](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-SetItemProperties)). We'll take some time in the near future to update all the documentation in this repository to use semicolons instead of pipes.
