### ISSUE TITLE
Use threads to improve buildSync.groovy performance

### ISSUE THREAD

**Issue by ebukoski** [JFrogDev/artifactory-user-plugins#82]
The buildSync.groovy script processes build files one at a time which can be very slow especially when populating new empty instances.  

With threads the build sync can be done in parallel and can result in orders of magnitude performance improvement.  

As an example our artifactory instance has 700,000 build entries which can take 7-10 days (168-240 hours) to process one build at a time.  With a pool of 100 threads, the same instance was populated in less then 18 hours.

**Comment by DarthFennec** [comment]
Closing this issue; as the PR was merged, this seems resolved.
